# -------------------------------
# ServiceAccount + RBAC
# -------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-pod-provisioner-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-pod-provisioner-clusterRole
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-pod-provisioner-rolebinding
subjects:
  - kind: ServiceAccount
    name: nfs-pod-provisioner-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nfs-pod-provisioner-clusterRole
  apiGroup: rbac.authorization.k8s.io
---
# -------------------------------
# Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-pod-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-pod-provisioner
  template:
    metadata:
      labels:
        app: nfs-pod-provisioner
    spec:
      serviceAccountName: nfs-pod-provisioner-sa
      containers:
      - name: nfs-pod-provisioner
        image: rkevin/nfs-subdir-external-provisioner:fix-k8s-1.20
        volumeMounts:
          - name: nfs-pod-provisioner-v
            mountPath: /persistentvolumes
        env:
          - name: PROVISIONER_NAME
            value: nfs-provisioner
          - name: NFS_SERVER
            value: 172.31.23.215        # Replace with your NFS server IP
          - name: NFS_PATH
            value: /mnt/nfs_share     # Replace with your NFS exported path
      volumes:
        - name: nfs-pod-provisioner-v
          nfs:
            server: 172.31.23.215    # Replace with your NFS server IP
            path: /mnt/nfs_share      # Replace with your NFS exported path
---
# -------------------------------
# StorageClass
# -------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-provisioner
parameters:
  archiveOnDelete: "false"
